### ISSUE TITLE
Error `could not find a storage path for doc` in logs

### ISSUE THREAD

**Issue by deurk** [carlosz1986/paperless-mailservice#29]
`mailservice-1  | 2024/12/04 22:15:31 warning: could not find a storage path for doc with id=1191, placeholders won't work`

Here is my configuration, and I'm using the latest version on dockerhub (2.0)
```
Paperless:
  InstanceURL: https://paperless.[REDACTED].com/
  InstanceToken: [REDACTED]
  ProcessedTagName: SentToPennylane
  AddQueueTagName: MailToPennylane
  UseCustomFilenameFormat: false
  Rules:
    - Name: "SendThemToPennylane"
      Tags:
        - MailToPennylane
      ReceiverAddress: "[REDACTED]"
Email:
  SMTPAddress: notifications@[REDACTED]
  SMTPServer: [REDACTED]
  SMTPPort: 465
  SMTPConnectionType: tls
  SMTPUser: "[REDACTED]"
  SMTPPassword: "[REDACTED]"
  MailBody: "Sent through Paperless"
  MailHeader: "Invoice/Receipt"
RunEveryXMinute: 1
```

Any idea what is missing? Thanks.
